on:
  schedule:
  - cron: "0 3 * * *"

name: Product & Community Registries Check

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  check-registry:
    name: Check registry entries
    # Temporary change for failure https://github.com/devfile/alizer/actions/runs/6230640715/job/16920449943
    # For more info take a look at: https://github.com/actions/runner-images/issues/6709
    runs-on: 'ubuntu-20.04'
    outputs:
      matrix: ${{ steps.get-stacks.outputs.matrix }}
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.5'
      - name: Run registries check
        id: build
        run: |
          make build
          make check_registry
